baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'YouTube-Commenter'
[Params]
  description = 'Enable Comments for every Youtube Video'
  motto = 'Never be silenced again!'
  about = "Don't let your voice be disabled. YouTube-Commenter is a chrome extension that gives you back the power to comment to videos on Youtube that have them disabled. Get back the power to comment! Never be silenced again!"
  favicon = "favicon.ico"
  site_logo = "YT-Commenter.png"
[Menu]
[[menu.main]]
  identifier = 'terms'
  name = 'terms of service'
  title = 'terms of service'
  url = '/terms'
[[menu.main]]
  identifier = 'privacy'
  name = 'privacy policy'
  title = 'privacy policy'
  url = '/privacy'
[[menu.main]]
  identifier = 'support'
  name = 'support'
  title = 'suport'
  url = '/support'
[[menu.main]]
  identifier = 'community guidelines'
  name = 'community guidelines'
  title = 'community guidelines'
  url = '/community_guidelines'